version: '3.7'

services:
    redmine:
        container_name: redmine
        build:
            context: .
            dockerfile: Dockerfile.redmine
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ${REDMINE_PATH_FILES:-./data/redmine/files}:/usr/src/redmine/public/files
            - ${REDMINE_PATH_LOG:-./data/redmine/log}:/usr/src/redmine/public/log
        environment:
            REDMINE_PLUGINS_MIGRATE: 1
            REDMINE_DB_POSTGRES: postgres
            REDMINE_DB_ENCODING: utf8
            REDMINE_DB_USERNAME: ${REDMINE_DB_USERNAME:-redmine}
            REDMINE_DB_PASSWORD: ${REDMINE_DB_PASSWORD:-redmine}
            TZ: Asia/Tokyo
        links:
            - postgres

    postgres:
        container_name: postgres_redmine
        build:
            context: .
            dockerfile: Dockerfile.postgres
        volumes:
            - ${POSTGRES_PATH_DB:-./data/postgres/db-data}:/var/lib/postgresql/data
            - ${POSTGRES_PATH_INITDB:-./data/postgres/initdb}:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD:-postgres}
            POSTGRES_DATABASE: redmine
            POSTGRES_USER: ${REDMINE_DB_USERNAME:-redmine}
            POSTGRES_PASSWORD: ${REDMINE_DB_PASSWORD:-redmine}
            TZ: Asia/Tokyo

volumes:
    redmine:
    postgres:
